twitter_app/config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :posts

  root 'sessions#new'
  get '/signup' => 'users#new'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

end

twitter_app/app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  validates :content, length: { maximum: 140 }
end

twitter_app/app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  has_secure_password
  validates :first_name, :email,  presence: true
  validates :email, :username, uniqueness: true
  validates :first_name, length: { minimum: 2 }
end

twitter_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

def current_user
  @current_user ||= User.find(session[:user_id]) if session[:user_id]
end

def require_user
  redirect_to '/login' unless current_user
end

end

twitter_app/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_user, only: [:index, :show]

  def index
  @posts = Post.all
  @post = Post.new
end

def show
  @post = Post.find(params[:id])
end

def new
  @post = Post.new
end

def create
  @post = Post.new( user_id: params[:user_id], content: params[:content])

  render json: @post.save

end

def edit
  @post = Post.find(params[:id])
end

def update
  @post = Post.find(params[:id])

  if @post.update(post_params)
    redirect_to @post
  else
    render 'edit'
  end
end

def destroy
  @post = Post.find(params[:id])
  @post.destroy

  redirect_to posts_path
end



private
  def post_params
    params.require(:post).permit(:content, :user_id)
  end
end

twitter_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

    def create
  @user = User.find_by_email(params[:session][:email])
  if @user && @user.authenticate(params[:session][:password])
    session[:user_id] = @user.id
    redirect_to '/posts'
  else
    redirect_to '/'
  end
end

  def destroy
    session[:user_id] = nil
  redirect_to '/'
  end
end

twitter_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to '/', notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :username)
  end
end

twitter_app/app/helpers/application_helper.rb
module ApplicationHelper
end

twitter_app/app/helpers/posts_helper.rb
module PostsHelper
end

twitter_app/app/helpers/sessions_helper.rb
module SessionsHelper
end

twitter_app/app/helpers/users_helper.rb
module UsersHelper
end

twitter_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TwitterApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
</head>
<body>

  <!-- Navigation -->
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#page-top">Start Bootstrap</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <!-- Your code here -->
                    <% if current_user %>
                      <li><%= current_user.email %></li>
                      <li><%= link_to "Log out", logout_path, method: "delete" %></li>
                    <% else %>
                      <li><%= link_to "Signup", 'signup' %></a></li>
                      <li><%= link_to "Login", 'login' %></a></li>
                    <% end %>
                    <li class="page-scroll">
                        <a href="#contact">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>


  <%= yield %>

  <script src="js/jquery.js"></script>
  <!-- Bootstrap Core JavaScript -->
  <script src="js/bootstrap.min.js"></script>
</body>
</html>

twitter_app/app/views/posts/_form.html.erb
<%= form_for(:post) do |f| %>
   <%= f.text_field :content, :placeholder => "140 characters or less..." %>
   <%= f.hidden_field :user_id, :value => current_user.id %>
   <%= f.submit "Tweet", id: "tweet-button", class: "btn-submit" %>
 <% end %>

twitter_app/app/views/posts/index.html.erb
<body class="index_container">
    <!-- Page Content -->
    <div class="container">
        <div class="row">
          <div class="col-md-3">
              <!-- Blog Categories Well -->
              <div class="index_well">
                  <h4 class="index_heading">Trending Categories</h4>
                  <div class="row">
                      <div class="col-lg-12">
                          <ul class="list-unstyled">
                              <li><a href="#">Category Name</a>
                              </li>
                              <li><a href="#">Category Name</a>
                              </li>
                              <li><a href="#">Category Name</a>
                              </li>
                              <li><a href="#">Category Name</a>
                              </li>
                          </ul>
                      </div>
                  </div>
                  <!-- /.row -->
              </div>

              <!-- Side Widget Well -->
              <div class="index_well">
                  <h4 class="index_heading">Side Widget Well</h4>
                  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore, perspiciatis adipisci accusamus laudantium odit aliquam repellat tempore quos aspernatur vero.</p>
              </div>

          </div>


            <!-- Blog Post Content Column -->
            <div class="col-lg-6">

              <div class="tweet_well">
                  <h4 class="index_heading">Tweet:</h4>
                   <%= form_for(:post, :html => { :id => "form-tweet" }) do |f| %>
              			  <%= f.text_field :content, id: "tweet-text", class: "tweet_text", :placeholder => "140 characters or less..." %>
                      <%= f.hidden_field :user_id, id: "user-id", :value => current_user.id %>
              			  <%= f.submit "Send Tweet", id: "tweet-button", class: "tweet_btn" %>
              			<% end %>
              </div>

                <hr>

                <!-- Tweets -->

                <div class="media">
                  <% @posts.reverse.each do |post| %>
                    <a class="pull-left" href="#">
                        <img class="media-object" src="http://placehold.it/64x64" alt="">
                    </a>
                    <div class="media-body">
                        <h4 class="media-heading"><%= post.user.first_name %>
                            <small>August 25, 2014 at 9:30 PM</small>
                        </h4>
                        <p class="tweet_content"><%= post.content %></p>
                    </div>
                    <hr>
                    <% end %>
                </div>
            </div>



            <!-- Blog Sidebar Widgets Column -->
            <div class="col-md-3">

                <!-- Blog Search Well -->
                <div class="index_well">
                    <h4 class="index_heading">Blog Search</h4>
                    <div class="input-group">
                        <input type="text" class="form-control">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button">
                                <span class="glyphicon glyphicon-search"></span>
                        </button>
                        </span>
                    </div>
                    <!-- /.input-group -->
                </div>

                <!-- Blog Categories Well -->
                <div class="index_well">
                    <h4 class="index_heading">Blog Categories</h4>
                    <div class="row">
                        <div class="col-lg-12">
                            <ul class="list-unstyled">
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <!-- /.row -->
                </div>

                <!-- Side Widget Well -->
                <div class="index_well">
                    <h4 class="index_heading">Side Widget Well</h4>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore, perspiciatis adipisci accusamus laudantium odit aliquam repellat tempore quos aspernatur vero.</p>
                </div>

            </div>

        </div>
        <!-- /.row -->

        <hr>




</body>

twitter_app/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

twitter_app/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

twitter_app/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

twitter_app/app/views/users/new.html.erb
<img src="assets/bg.jpg" class="background-image">

<div class="signup">
  <div class="container">
    <div class="row">
        <div class="col-lg-7 col-lg-offset-2 text-center">
          <br>
          <br>
          <div class="form">
          <h1 id="header">Sign up</h1>

          <%= form_for(@user) do |f| %>
            <%= f.text_field :first_name, class: "sign_up", :placeholder => "First name" %>
            <%= f.text_field :last_name, class: "sign_up", :placeholder => "Last name" %>
            <%= f.email_field :email, class: "sign_up", :placeholder => "Email" %>
            <%= f.text_field :username, class: "sign_up", :placeholder => "Username" %>
            <%= f.password_field :password, class: "sign_up", :placeholder => "Password" %>
            <%= f.submit "Create an account", class: "btn-submit" %>
            <% end %>

          </div>
        </div>
    </div>
  </div>
</div>

twitter_app/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>